CREATE DATABASE IF NOT EXISTS omnifit;
USE omnifit;

CREATE TABLE Users (
	id INT AUTO_INCREMENT PRIMARY KEY, 
	username VARCHAR(50) UNIQUE NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL
);

CREATE TABLE Workouts(
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    rpe FLOAT DEFAULT 5.0,
	date_created DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);


CREATE TABLE Sets (
	id INT AUTO_INCREMENT PRIMARY KEY,
	workoutID INT NOT NULL, 
	exerciseName VARCHAR(100) NOT NULL, 
    muscleGroup VARCHAR(50),
    setsCount INT,
	reps VARCHAR(100), 
	recoveryBetweenSets INT, 
	recoveryExercise INT, 
	FOREIGN KEY (workoutID) REFERENCES Workouts(id) ON DELETE CASCADE
);


CREATE TABLE Goals(
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	muscle_group VARCHAR(50),
	target_sets INT,
	FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE RPE_Log(
	id INT AUTO_INCREMENT PRIMARY KEY,
	workout_id INT NOT NULL,
	rpe_value INT CHECK(rpe_value BETWEEN 1 AND 10),
	FOREIGN KEY (workout_id) REFERENCES Workouts(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS NutritionLog (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    meal_name VARCHAR(100) NOT NULL DEFAULT 'Meal',
    calories INT NOT NULL DEFAULT 0,
    proteins INT NOT NULL DEFAULT 0,
    carbs INT NOT NULL DEFAULT 0,
    fats INT NOT NULL DEFAULT 0,
    date_logged DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS NutritionGoals (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE, 
    daily_calorie_goal INT NOT NULL DEFAULT 2400,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS HydrationLog (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    amount INT NOT NULL, 
    date_logged DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS HydrationGoals (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    daily_water_goal INT NOT NULL DEFAULT 2500,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MeditationLog (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    minutes INT NOT NULL,
    date_logged DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MeditationGoals (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    daily_minutes_goal INT NOT NULL DEFAULT 30,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

INSERT IGNORE INTO Users (id, username, email, password) VALUES (1, 'testuser', 'test@test.com', '12345');