// Data model representing a user's fitness goal for a specific muscle group.
class Goal {
  int? id; // Unique identifier for the goal (usually auto-generated by SQL).
  int userId; // The ID of the user who set the goal.
  String muscleGroup; // Targeted muscle group (e.g., "Chest", "Legs").
  int targetSets; // Target number of sets the user wants to complete.

  // Constructor to initialize a new Goal instance.
  Goal({
    this.id,
    required this.userId,
    required this.muscleGroup,
    required this.targetSets,
  });

  // Factory constructor that translates a raw MySQL database row into a Dart object.
  factory Goal.fromRow(Map<String, dynamic> row) {
    return Goal(
      id: row['id'], // Extracts the 'id' column.
      userId: row['user_id'], // Extracts the 'user_id' column.
      muscleGroup: row['muscle_group'], // Extracts the 'muscle_group' column.
      targetSets: row['target_sets'], // Extracts the 'target_sets' column.
    );
  }
}
