// Data model representing a user's daily hydration log.
class HydrationLog {
  int? id; // Unique identifier for the log (usually auto-generated by SQL).
  int userId; // The ID of the user who logged the hydration.
  DateTime? dateLogged; // The date and time when the water intake was logged.
  int waterMl; // Amount of water consumed in milliliters (ml).

  // Constructor to initialize a new HydrationLog instance.
  HydrationLog({
    this.id,
    required this.userId,
    this.dateLogged,
    required this.waterMl,
  });

  // Factory constructor that translates a raw MySQL database row into a Dart object.
  factory HydrationLog.fromRow(Map<String, dynamic> row) {
    return HydrationLog(
      id: row['id'], // Extracts the 'id' column.
      userId: row['user_id'], // Extracts the 'user_id' column.
      dateLogged: row['date_logged'], // Extracts the 'date_logged' column.
      waterMl: row['water_ml'], // Extracts the 'water_ml' column.
    );
  }
}
