// Data model representing a meditation or stretching session log.
class MeditationLog {
  int? id; // Unique identifier for the log (usually auto-generated by SQL).
  int userId; // The ID of the user who performed the session.
  DateTime? dateLogged; // The date and time when the session was logged.
  int
  durationMinutes; // Duration of the meditation or stretching session in minutes.

  // Constructor to initialize a new MeditationLog instance.
  MeditationLog({
    this.id,
    required this.userId,
    this.dateLogged,
    required this.durationMinutes,
  });

  // Factory constructor that translates a raw MySQL database row into a Dart object.
  factory MeditationLog.fromRow(Map<String, dynamic> row) {
    return MeditationLog(
      id: row['id'], // Extracts the 'id' column.
      userId: row['user_id'], // Extracts the 'user_id' column.
      dateLogged: row['date_logged'], // Extracts the 'date_logged' column.
      durationMinutes:
          row['duration_minutes'], // Make sure this matches your SQL column name exactly.
    );
  }
}
