// Data model representing a user's daily nutrition log.
class NutritionLog {
  int? id; // Unique identifier for the log (usually auto-generated by SQL).
  int userId; // The ID of the user who logged the meals.
  DateTime? dateLogged; // The date and time when the nutrition was logged.
  int calories; // Total amount of calories consumed.

  // Constructor to initialize a new NutritionLog instance.
  NutritionLog({
    this.id,
    required this.userId,
    this.dateLogged,
    required this.calories,
  });

  // Factory constructor that translates a raw MySQL database row into a Dart object.
  factory NutritionLog.fromRow(Map<String, dynamic> row) {
    return NutritionLog(
      id: row['id'], // Extracts the 'id' column.
      userId: row['user_id'], // Extracts the 'user_id' column.
      dateLogged: row['date_logged'], // Extracts the 'date_logged' column.
      calories: row['calories'], // Extracts the 'calories' column.
    );
  }
}
