// Data model representing a user's Rate of Perceived Exertion (RPE) for a specific workout.
class RpeLog {
  int? id; // Unique identifier for the log (usually auto-generated by SQL).
  int workoutId; // The ID of the workout the user just completed.
  int
  rpeValue; // The perceived effort score, typically on a scale from 1 to 10.

  // Constructor to initialize a new RpeLog instance.
  RpeLog({this.id, required this.workoutId, required this.rpeValue});

  // Factory constructor that translates a raw MySQL database row into a Dart object.
  factory RpeLog.fromRow(Map<String, dynamic> row) {
    return RpeLog(
      id: row['id'], // Extracts the 'id' column.
      workoutId: row['workout_id'], // Extracts the 'workout_id' column.
      rpeValue: row['rpe_value'], // Extracts the 'rpe_value' column.
    );
  }
}
