// Data model representing a specific exercise set within a workout.
class ExerciseSet {
  int? id; // Unique identifier for the set (usually auto-generated by SQL).
  int workoutId; // The ID of the workout this set belongs to.
  String
  exerciseName; // The name of the exercise performed (e.g., "Bench Press").
  int setOrder; // The sequence order of this set within the workout.
  int reps; // The number of repetitions performed in this set.
  double weight; // The weight used for the set.

  // Constructor to initialize a new ExerciseSet instance.
  ExerciseSet({
    this.id,
    required this.workoutId,
    required this.exerciseName,
    required this.setOrder,
    required this.reps,
    this.weight = 0.0,
  });

  // Factory constructor that translates a raw MySQL database row into a Dart object.
  factory ExerciseSet.fromRow(Map<String, dynamic> row) {
    return ExerciseSet(
      id: row['id'], // Extracts the 'id' column.
      workoutId:
          row['workoutID'], // Extracts the 'workoutID' column (must match SQL exactly).
      exerciseName: row['exerciseName'], // Extracts the 'exerciseName' column.
      setOrder: row['setOrder'], // Extracts the 'setOrder' column.
      reps: row['reps'], // Extracts the 'reps' column.
      weight: (row['weight'] as num)
          .toDouble(), // Safely parses the 'weight' column to a double.
    );
  }
}
