// Data model representing a registered user in the application.
class User {
  int? id; // Unique identifier for the user (usually auto-generated by SQL).
  String username; // The user's chosen display name.
  String email; // The user's email address used for login and contact.
  String
  password; // The user's password (should ideally be hashed in a real app).

  // Constructor to initialize a new User instance.
  User({
    this.id,
    required this.username,
    required this.email,
    required this.password,
  });

  // Factory constructor that translates a raw MySQL database row into a Dart object.
  factory User.fromRow(Map<String, dynamic> row) {
    return User(
      id: row['id'], // Extracts the 'id' column.
      username: row['username'], // Extracts the 'username' column.
      email: row['email'], // Extracts the 'email' column.
      password: row['password'], // Extracts the 'password' column.
    );
  }

  // Converts the Dart object back into a Map (useful for JSON serialization or inserts).
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'username': username,
      'email': email,
      'password': password,
    };
  }
}
