// Data model representing a user's workout session.
class Workout {
  int? id; // Unique identifier for the workout (usually auto-generated by SQL).
  int userId; // The ID of the user who performed the workout.
  DateTime? dateCreated; // The date and time when the workout took place.

  // Constructor to initialize a new Workout instance.
  Workout({this.id, required this.userId, this.dateCreated});

  // Factory constructor that translates a raw MySQL database row into a Dart object.
  factory Workout.fromRow(Map<String, dynamic> row) {
    return Workout(
      id: row['id'], // Extracts the 'id' column.
      userId: row['user_id'], // Extracts the 'user_id' column.
      dateCreated: row['date_created'], // Extracts the 'date_created' column.
    );
  }
}
